### ISSUE TITLE
libcurl3

### ISSUE THREAD

**Issue by BoiseComputer** [BoiseComputer/atlas-server-tools#1]
ATLAS requires libcurl3, but libcurl4 is current with Ubuntu. Error messages  occur in ARK Server Tools when using libcurl3 and error messages occur in ATLAS Server Tools when using libcurl4.

Most likely this is due to the version of Unreal Engine (4.5) ATLAS is currently developed under.

**Comment by angryce** [comment]
A temporary fix (until they actually update it) seems to be using this (at least on ubuntu servers (I presume debian as well but haven't actually tried it there)

https://launchpad.net/~xapienz/+archive/ubuntu/curl34

**Comment by BoiseComputer** [comment]
That did allow a server to start. I will use this to continue testing the script. Thank you.

**Comment by BoiseComputer** [comment]
Here is a response regarding the out of date libraries. [https://twitter.com/Jatheish/status/1090502189972369408](https://twitter.com/Jatheish/status/1090502189972369408)
Having dug into this, the awslib files were compiled using libcurl3. Hopefully with the update releasing soon, this will fix the issue.

**Comment by BoiseComputer** [comment]
This seems to have been corrected in recent updates. Closing topic.
