### ISSUE TITLE
[Request] Back up Redis and ServerGrid

### ISSUE THREAD

**Issue by Andargor** [BoiseComputer/atlas-server-tools#10]
The backups currently only save the ocean and two ini files. To be able to restore a server completely, the Redis database (ATLAS/AtlasTools/RedisDatabase/redis_atlasdb.rdb) should be flushed to disk and saved, and so should the grid files (ATLAS/ShooterGame/ServerGrid*).

**Comment by Andargor** [comment]
I would add that saving the atlasmanager.cfg and instance files would also be necessary to have a complete backup.

**Comment by Andargor** [comment]
One more thing, each tile's Config file and ocean tile, e.g. ShooterGame/Saved/A1/Config, ShooterGame/Saved/A1/ocean.atlas

The other .atlas files seem to keep the fog of war data, but that is not really important for a restore considering the size of those files.

**Comment by BoiseComputer** [comment]
I will change how the backup procedures work by having it backup the json files, tribe files, map images, etc. since backing up an individual server doesn't seem to matter as much. Users will probably still want to have the ability to backup the server files as well, since it would cause them to lose buildings, ships, etc. if they aren't. I think what I will do is have it backup the important files when backing up the main instance and then just the map specific files for each other instance. Will keep you updated.

**Comment by BoiseComputer** [comment]
Redis itself is fairly isolated, so I think the current method for backing it up is correct. Just be sure to use the  redis --backup option and backup @all command once I have that reworked. This will have a redis backup, and then a backup of all important files to do a fairly comprehensive restore.

**Comment by BoiseComputer** [comment]
When performing a backup, if you are backing up the main instance, it will include the atlasmanager.cfg, server grid .json file,  and map files. Each backup also now includes its .cfg file for that instance. For the redis backup, I now include the redis.conf file to help if a recovery is needed.
So a full backup could be done with this command:  `atlasmanager backup @all redis --backup`

**Comment by Andargor** [comment]
Great stuff, seems to work. One thing is missing however, the ServerGrid.ServerOnly.json file (with the Redis credentials).

EDIT: It would be great if the redis backup could call `redis-cli -a foobared save` if you don't already to flush to disk, the password foobared is the default from the server grid tool, but can be obtained from the ServerGrid.ServerOnly.json file.

**Comment by BoiseComputer** [comment]
Good catch on the ServerGrid.ServerOnly.json file. I will add that now.

So, currently it is doing this: `redis-cli -p "$redisPort" -a "$redisPassword" bgsave`.
[https://redis.io/commands/save](https://redis.io/commands/save) They recommended against doing save, but what I could do is have the backup delay a few seconds in order to allow it time to dump on a large database.

**Comment by BoiseComputer** [comment]
v1.8.5.3
I have added a 2 second delay before the redis db is copied.
I have also included the ServerOnly file in the backup.

**Comment by Andargor** [comment]
Thanks, all seems to be there, though the rdb file has a curious path inside the tar file, I had to go under "." then "_" to find it.

EDIT: I'm guessing it should be in the same directory as the redis.conf file?

**Comment by BoiseComputer** [comment]
Tomorrow I will clean up how it copies it. That should fix that issue and have the files in the base folder of the compress file. It will also give more direct feedback on the status of copying the file.

**Comment by BoiseComputer** [comment]
I improved how it copies files for the redis backup in v1.8.5.4 and it is uploaded.
It will put the two files in the root of the bzip. Feel free to give it a try and let me know how it works.

**Comment by Andargor** [comment]
Your changes seems to have worked, thanks. I think this is functionally working, and can be closed. I do have some improvements to recommend, however.

Last night I was expanding our server's grid, and after some corruption I had to revert to a previous backup. It was more tedious than I expected since the files are not in the same directory structure, and I had to manually slide them into their proper place. Further, the timestamps did not exactly match (a few seconds apart) and considering I performed a few backups in quick succession, I made mistakes and had to restart over again.

I understand you are shoehorning arkmanager's backup scheme, but Atlas needs another approach. The ideal situation for me last night would have been an archive where I just dragged and dropped the directories under my ATLAS folder. The following would have given me the exact structure I needed, minus the atlasmanager configuration files:

From the ATLAS directory, run
```bash
tar cvjpf atlas-backup.$(date +%Y%m%d%H%M%S).tar.bz2 AtlasTools/RedisDatabase/*.rdb AtlasTools/RedisDatabase/redis.conf ShooterGame/ServerGrid* ShooterGame/Saved/*/ocean.atlas ShooterGame/Saved/*/Config`
```
Of course redis bgsave would have to be done previously, and the atlasmanager configuration could be saved separately (perhaps with the same timestamp reused from a variable), or added to the same archive at root using `tar rf`.

My $0.02

EDIT: sorry, you can't update a compressed tar archive, so I guess the atlasmanager config would have to be separate, unless you tar first and then compress.
