### ISSUE TITLE
Server Connection Timeout

### ISSUE THREAD

**Issue by Mac1508** [BoiseComputer/atlas-server-tools#23]
Hi, I followed your steps, all appears to have worked no errors during the process. I get as far as starting all and status shows all are up and running, I can even see the server when I add the IP to favourites.

However I always get a timeout not sure what is happening. All logs attached.

thanks
Mac
[log.txt](https://github.com/BoiseComputer/atlas-server-tools/files/4003511/log.txt)
[Manager.log](https://github.com/BoiseComputer/atlas-server-tools/files/4003512/Manager.log)
[server.log](https://github.com/BoiseComputer/atlas-server-tools/files/4003513/server.log)

**Comment by Mac1508** [comment]
status info
[status.txt](https://github.com/BoiseComputer/atlas-server-tools/files/4003518/status.txt)

**Comment by wartexesports** [comment]
I have exactly the same problem. Only with me he connects everything redis but he can not connect to the server.

**Comment by Mac1508** [comment]
yeah I can see the server in my favourites all the info is there. I can attempt to connect but then connection timeout. very strange

**Comment by BoiseComputer** [comment]
Do you have a log file here? /var/log/atlastools/atlasserver.log That might give some additional info. Also perhaps here: /var/log/atlastools/atlasmanager.log

**Comment by wartexesports** [comment]
yes here 
[atlasmanager.log](https://github.com/BoiseComputer/atlas-server-tools/files/4005619/atlasmanager.log)

**Comment by wartexesports** [comment]
I know that was not correct at the beginning but changed it directly as you can see with the path

**Comment by wartexesports** [comment]
somehow he doesn't want to write anything to the database. Think that's the problem that you can't join

**Comment by BoiseComputer** [comment]
What would probably be easiest is if we did some troubleshooting in my Discord. I am heading to work now, but will be available after work this evening. I made a channel for atlas-server-tools where we can discuss it and troubleshoot it.
https://discord.gg/NbpSPyq

**Comment by Mac1508** [comment]
Hi that would be great. Above in my first link should be all the logs you mentioned

**Comment by BoiseComputer** [comment]
I am hoping that the upcoming patch from Grapeshot will include a fix for the Linux server client.

**Comment by BoiseComputer** [comment]
The Linux server client now works again. Update Atlas and try running it again.
