### ISSUE TITLE
Question: Is Atlas still working nativ under Linux?

### ISSUE THREAD

**Issue by LotekHeavy** [BoiseComputer/atlas-server-tools#26]
I heard some comments that since the mega update atlas server under linux are not working correctly (https://www.playatlas.com/index.php?/forums/topic/108954-players-cannot-connect-to-linux-dedicated-servers/&tab=comments#comment-463086) 

Is this tool still working for a fresh install or should I better look for a solution with wine?

**Comment by BoiseComputer** [comment]
Currently the Linux client seems to be broken. Until they fix it, there is not much we can do to get it running natively.
