### ISSUE TITLE
Switching Clusters

### ISSUE THREAD

**Issue by Liv33viL** [BoiseComputer/atlas-server-tools#29]
Hey there,
We have set up the server (2x2) on an external server 32GB of RAM, hexacore processor, 500Mbit internet connection. Playing on it with up to 5 players. So this is more than enough.
Edit: Ubuntu 18.04

Everything is workin just fine, no lags at all.

But there are still two issues we cant figure out:

1. The treasure maps have been broken but we were able to fix them. Anyways if we go to the needed Location there is no event spawning.

2. Cluster switching works fine..... As long if we switch it one by one. If we are 2 or more on the same ship we are getting timed out and can't rejoin. When the server is restarted afterwards all players spawn on the new cluster.
I've found a thread where someone said it is needed to set the seamless IP in atlasmanger.cfg but it didnt work. Wasn't able to find other mentions to fix it. Mybe just looking for the wrong keywords?

Let me know which files are needed.

Greatings

**Comment by Liv33viL** [comment]
One more thing  just came to my mind:

A server password is set at every cfg file where it was beeing able to put in and all are uncommented. Nevertheless the server refuses to set it. It is accessible without typing in a pw.

If I use "atlasmanager run"  "?ServerPassword=tkpkprivat" is shown in the start options. But no password is set.

**Comment by Liv33viL** [comment]
beautiful - not even an answer in 4 years <3 - i'll close this :)

**Comment by Liv33viL** [comment]
Nice, not even a comment or question in 4 years - anyway, lets close this :)

**Comment by BoiseComputer** [comment]
> Nice, not even a comment or question in 4 years - anyway, lets close this :)

Hi Liv33vil,
I stopped maintaining the script due to the lack of Linux support. There were constant issues, but they were on the development side of Atlas. Sorry for any frustration this has caused.
- Brian
