### ISSUE TITLE
Map Saves

### ISSUE THREAD

**Issue by BoiseComputer** [BoiseComputer/atlas-server-tools#3]
Currently a bug with ATLAS that does not allow you to start up a previous map save. Requires you to delete map.

**Comment by Destructor** [comment]
No news for this bug ?

**Comment by BoiseComputer** [comment]
Here is a response from Jat regarding the bug: https://twitter.com/Jatheish/status/1090502189972369408
They have acknowledged it and we should expect a fix soon.

**Comment by BoiseComputer** [comment]
This issue has now been resolved. You will be able to save and reload save games after the most recent update.
https://twitter.com/Jatheish/status/1090518161156386819
