### ISSUE TITLE
Port error -1

### ISSUE THREAD

**Issue by Destructor** [BoiseComputer/atlas-server-tools#4]
Hi,

Currently I choose port 5750, but when the server starts it puts me 5749.

Can you correct that?

**Comment by BoiseComputer** [comment]
Can you see what ports you have set in your ServerGrid.json file? Is that set to 5749?

**Comment by Destructor** [comment]
In m’y servergrid 5750..., main.cfg 5750. 
Start log 5749....

**Comment by BoiseComputer** [comment]
Applied the fix. Run the upgrade-tools command and it should fix it.

**Comment by BoiseComputer** [comment]
Once you test it let me know and I can mark this a closed.

**Comment by Destructor** [comment]
thanks it's work ;)
