### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by angryce** [BoiseComputer/atlas-server-tools#5]
Could you make it so you could configure which servers to start after "main"

For instance;
Server-order: Server1,Server2,Server3,Server4

( I assume its not really important as long as main/server1 is running, felt like asking nonetheless tho)

**Comment by BoiseComputer** [comment]
Hi angryce,
The main instance will start first and then instances will list in alphabetical order after that. If you would like them to start in a specific order, you could name as you have shown in the example above. If server1 is main, it would do it in that order. If Server4 is main, it would start in the order of Server4,Server1,Server2,Server3. If you keep very different names for your instances, you could do something like: 1servername, 2differentname,3somethingelse,etc. This would allow you to name the instances whatever you wish, while maintaining a specific start order.
Let me know if this covers your request.
