### ISSUE TITLE
[Request] Changelogs

### ISSUE THREAD

**Issue by BlitzCentral** [BoiseComputer/atlas-server-tools#6]
Can a command be added to the AtlasManager tool to display the change logs for the Linux files of the Atlas server?

Example: root@atlas:~$ atlasmanager change-log @{Server Name/s}

Whether this can be pulled directly from a site or it will have to be added automatically each time you update the tools. 

Go wild! 

- Blitz

**Comment by BoiseComputer** [comment]
I will have to look around to see if I can find a place other than their blog where they are putting a text version of their changelog. If so, I could attempt to pull that information. Currently I have not seen a nice place they are providing it yet.

Example: https://steamdb.info/patchnotes/3513039/
On Steam they don't post patch notes. Makes it more difficult to parse without a decent, clean source for the info. I will keep you updated.

**Comment by f0rkz** [comment]
Commit messages should be pretty clear on what's changed. Github is pretty awesome about providing the tools necessary to see what exactly is going on with a project rather than engineering a solution for tooling.

Just my $0.02

**Comment by BoiseComputer** [comment]
The main issue we are having is that he wants a message with the changes ATLAS has implemented that version. Currently Grapeshot doesn't put this information in an easy place for me to grab and display to the client. I put change logs for every update to atlasmanager. Just not for checking for updates to ATLAS servers.
