### ISSUE TITLE
Install or update not work

### ISSUE THREAD

**Issue by Destructor** [BoiseComputer/atlas-server-tools#7]
hi,

since the last version of the tool atlasmanger install or update it does not work anymore.
I have no logs....

Regards,

**Comment by BoiseComputer** [comment]
What release tag does "atlasmanager --version" show you?

**Comment by Destructor** [comment]
Version: 1.8.3.7

**Comment by BoiseComputer** [comment]
Do you get anything when you type "atlasmanager checkupdate"?

**Comment by BoiseComputer** [comment]
If you would like to troubleshoot this in person, feel free to message me on Discord. BoiseComputer#3471
