### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by jerome80** [BoiseComputer/atlas-server-tools#9]
Sai can add this function thank you

Server Launch Option which locks the Fountain of Youth to one Golden Age Ruins server:  -AlwaysActiveFountainsOfYouth

**Comment by BoiseComputer** [comment]
Hi jerome,
To activate this on all of your servers, place the following line in the  /etc/atlasmanager/atlasmanager.cfg file.

atlasflag_AlwaysActiveFountainsOfYouth=true

If this option needs to run on only one server, place it in the appropriate instance .cfg file in /etc/atlasmanager/instances/

**Comment by jerome80** [comment]
thank you
